namespace:
  name: production
 
service:
  port: 80
  type: LoadBalancer

image:
  repository: oyelowo/tech-trends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 60m
    memory: 256Mi
