namespace:
  name: sandbox
 
service:
  port: 7111
  type: LoadBalancer

image:
  repository: nginx 
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi
