namespace:
  name: sandbox
 
service:
  port: 7111
  type: LoadBalancer

image:
  repository: oyelowo/tech-trends
  tag: v1.0.0
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 256Mi
