apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml

images:
- name: oyelowo/tech-trends
  newName: oyelowo/tech-trends
  newTag: main-c3f9834d96a53c27c2d2663f6eadebff9c122ac9
