apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml

images:
- name: oyelowo/tech-trends
  newName: oyelowo/tech-trends
  newTag: main-2378dc884a9d91c4dd0a25b2ab166dddfaab952f
