apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
images:
- name: tech
  newName: oyelowo/tech-trends
  newTag: main-66656e8d94a445639fe82699159fdee279d91147
