apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- namespace.yaml
- service.yaml
images:
- name: oyelowo/tech-trends
  newName: oyelowo/tech-trends
  newTag: main-f5a2c78ca3a4e71d0bc4d93de910ee344e5daa25
