apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-trends-pvc-volume
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
    #finalizers:
  #- kubernetes.io/pv-protection

