apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-trends-pv-volume
  labels:
    type: local
spec:
  volumeMode: File
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/dev"

