apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pv-claim
  labels:
    app: sqlite
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  # selector:
  #   matchLabels:
  #     type: local

    #finalizers:
  #- kubernetes.io/pv-protection

