apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  labels:
    type: local
    app: sqlite
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/dev"
    # type: FileOrCreate

