apiVersion: v1
kind: Service
metadata:
  name: tech-trends-service
  namespace: default
  labels:
    app: tech-trends
    tag: web
spec:
  selector:
    app: tech-trends-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3111
    nodePort: 30009
  type: NodePort
