apiVersion: v1
kind: Service
metadata:
  name: tech-trends-service
  namespace: test
  labels:
    app: tech-trends
    tag: web
spec:
  selector:
    app: tech-trends
    tag: web
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
