apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-trends-web
  namespace: default
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: tech-trends
        resources:
          requests:
            cpu: 250m
            memory: "256M"
          limits:
            cpu: 500m
            memory: "0.5G"
        volumeMounts:
        - name: web-volume-prod
          mountPath: .
      volumes:
      - name: web-volume-prod
        hostPath:
          path: /tech-trends-prod/data
