apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-trends-web
  namespace: default
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: tech-trends
        resources:
          requests:
            cpu: 250m
            memory: "256M"
          limits:
            cpu: 100m
            memory: "0.5G"
