apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
   # Use  storage class and NFS or cloud provider storage for production application.
   # Here we are using a local virtual machine which is a single node.
  hostPath:
    path: "/mnt/data/prod/database.db"
    type: FileOrCreate
