apiVersion: v1
kind: Service
metadata:
  name: tech-trends-service
  namespace: prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30020
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30021
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort
