apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tech-trends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/tech-trends/environments/staging
    repoURL: https://github.com/Oyelowo/tech-trends 
    targetRevision: HEAD
