apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tech-trends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      version: v3.5.4
    path: kustomize/tech-trends/sandbox
    repoURL: https://github.com/Oyelowo/tech-trends 
    targetRevision: HEAD
