namespace:
  name: production
 
service:
  port: 7111
  type: ClusterIP

image:
  repository: tech-trends
  tag: web-
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 60m
    memory: 256Mi

configmap:
  data: "version: 1.1.0"
