apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-trends-web
  namespace: default
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: tech-trends
        resources:
          requests:
            cpu: 250m
            memory: "256M"
          limits:
            cpu: 2
            memory: "1G"
