apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
  - persistent-volume.yaml
  
nameSuffix: -staging
namespace: staging
