apiVersion: v1
kind: Service
metadata:
  name: tech-trends-service
spec:
  ports:
  - name: http
    port: 3111
    protocol: TCP
    targetPort: 3111
    nodePort: 30040
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3111
    nodePort: 30041
